apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: LoadGenerator
  namespace: LoadGenerator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: LoadGenerator
  minReplicas: 2  
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50